#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SaveToSql.Resource", IsApplication=true)]

namespace SaveToSql
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Resource.String.ApplicationName = global::SaveToSql.Resource.String.ApplicationName;
			global::SQLite.Resource.String.Hello = global::SaveToSql.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int btnCamera = 2131034118;
			
			// aapt resource value: 0x7f05000b
			public const int btnSave = 2131034123;
			
			// aapt resource value: 0x7f050001
			public const int editDate = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int editDesc = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int editLat = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int editLong = 2131034122;
			
			// aapt resource value: 0x7f050005
			public const int imageView1 = 2131034117;
			
			// aapt resource value: 0x7f05000c
			public const int textMessage = 2131034124;
			
			// aapt resource value: 0x7f050000
			public const int textView1 = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int textView2 = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int textView3 = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int textView4 = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int textViewLong = 2131034121;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int app_name = 2130968579;
			
			// aapt resource value: 0x7f04000a
			public const int button_camera = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int button_save = 2130968587;
			
			// aapt resource value: 0x7f040002
			public const int hello = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int lable_date = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int lable_desc = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int lable_image = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int lable_lat = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int lable_long = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int lable_processed = 2130968585;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
